const tarsasok = [
    "A bűvös rengeteg;(2 fős)",
    "A rettegés éjszakája: Vérfarkas; (3-10 fő)",
    "A tiltott sivatag;(2 - 4 fő)",
    "A tiltott sziget;(2 - 4 fő)",
    "Azul;(2 - 4 fő)",
    "Black friday;(2 - 4 fő)",
    "Carcassone: Big box;(2 - 6 fő)",
    "Csorda szellem;(4 - 20 fő)",
    "Cthulhu: A halandó halál;(1 - 5 fő)",
    "Fenékig;(3 + fő)",
    "Fogda szappant;(3 - 6 fő)",
    "FRIENDS - Bumm szítál kvíz;(3 - 6 fő)",
    "Kaméleon;(3 - 8 fő)",
    "Lángművesek;(1 - 5 fő)",
    "Légy résen;(4 - 12 fő)",
    "Magic the Gathering;(4 pakli)(2 - 4 fő)",
    "Marvel: Végtelen kesztyű;(2 - 6 fő)",
    "Monopoly: A világ csodái;(2 - 8 fő)",
    "Munchkin(+ Fajtalan fejsze kieg);(3 - 6 fő)",
    "Munchkin Warhammer 40k;(3 - 6 fő)",
    "New phone, who dis ?;(3 - 20 fő)",
    "Old London Bridge;(2 - 4 fő)",
    "Operators;(2 - 10 fő)",
    "Párizs;(2 fős)",
    "Police 07;(2 - 6 fő)",
    "Sajtra szállás;(1 - 5 fő)",
    "Sárkányok erdeje;(2 - 4 fő)",
    "Schotten totten;(2 fős)",
    "Shit happens;(2 - 8 fő)",
    "Spicces skiccek;(2 - 8 fő)",
    "Ticket to ride Európa;(2 - 5 fő)",
    "Titkos kód;(2 fő)",
    "Tokió királya;(2 - 6 fő)",
    "Trónok harca: Westerosi intrikák;(2 - 6 fő)",
    "Unmatched: Árny és köd;(2 - 4 fő) *",
    "Unmatched: Houdini vs A Dzsin;(2 fő) *",
    "Unmatched: Legendák ligája első felvonás;(2 - 4 fő) *",
    "Uno flip;(2 - 10 fő)",
    "Végzetek;(1 - 3 fő)",
    "20 másodperc totál káosz;(5 - 20 fő)"
]